# Generated by Django 4.1.2 on 2023-06-27 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("nombre", models.CharField(max_length=30, verbose_name="Nombre")),
                (
                    "direccion",
                    models.CharField(max_length=30, verbose_name="Dirección"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Producto",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=25, verbose_name="Nombre producto"),
                ),
                ("stock", models.IntegerField(verbose_name="Stock")),
                (
                    "categoria",
                    models.CharField(max_length=20, verbose_name="Categoría"),
                ),
                ("imagen", models.URLField(blank=True, null=True, verbose_name="Foto")),
                ("precio", models.CharField(max_length=6, verbose_name="Precio")),
                ("estado", models.BooleanField(verbose_name="Estado")),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="CarritoProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "carrito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos_api.carrito",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos_api.producto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="carrito",
            name="productos",
            field=models.ManyToManyField(to="productos_api.producto"),
        ),
    ]
