# Generated by Django 4.1.2 on 2023-06-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_api', '0002_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(max_length=6, verbose_name='stock'),
        ),
    ]
