# Generated by Django 4.1.2 on 2023-06-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_api', '0004_alter_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.JSONField(default=list),
        ),
    ]
