# Generated by Django 4.1.2 on 2023-06-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_api', '0008_alter_carrito_options_alter_producto_idproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.CharField(max_length=6, verbose_name='precio'),
        ),
    ]
