# Generated by Django 4.1.2 on 2023-06-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_api', '0010_alter_producto_idproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='dirección',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='carrito',
            name='nombre',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='idProducto'),
        ),
    ]
