# Generated by Django 4.1.2 on 2023-06-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_api', '0011_carrito_dirección_carrito_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='dirección',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
