# Generated by Django 4.1.2 on 2023-06-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_api', '0012_alter_carrito_dirección_alter_carrito_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='dirección',
        ),
        migrations.AddField(
            model_name='carrito',
            name='direccion',
            field=models.CharField(default=False, max_length=30, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
