# Generated by Django 4.1.2 on 2023-06-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_api', '0013_remove_carrito_dirección_carrito_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='direccion',
            field=models.CharField(max_length=30, verbose_name='Dirección'),
        ),
    ]
