# Generated by Django 4.1.2 on 2023-06-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_api', '0014_alter_carrito_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='productos',
        ),
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(to='productos_api.producto'),
        ),
    ]
