# Generated by Django 4.1.2 on 2023-06-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos_api', '0016_alter_producto_categoria_alter_producto_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='idProducto',
            new_name='id',
        ),
    ]
